version: '3.7'

services:
  redis-server:
    image: 'redis'
  ui:
    restart: always
    build: './ui'
    ports: 
      - "80:80"
  live-video:
    restart: always
    build: './live-video'
    ports:
      - "8080:8080"